### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by v1m** [distributedweaknessfiling/dwf-workflow#10]
1. explicitly define the abbreviations: DWF, CAN, CVE etc.
-- Perhaps we can use definitions from here: https://www.first.org/global/sigs/vulnerability-coordination/multiparty/guidelines-v1.1
-- your podcast goes into how the acronym "DWF" was coined 👍 

2. I guess this has already been thought over, but the acronym CVE has a long established meaning of being associated with MITRE ecosystem. Perhaps, DWF should not use the same acronym. DWF could use: DWF_CAN and DWF_CVE (or some naming scheme like that to avoid confusion between Mitre-CVE and DWF-CVE). eg.: I can easily see how folks may be confused and take a DWF-CVE question to Mitre or the other way around.

3. > DWF IDs take the form of CAN or CVE, then a 4 digit year YYYY, then an integer identifier XXXXXXX. The integers start at 1000000, anything below one million is a MITRE CVE ID. Anything above one million is a DWF ID. So for example CVE-2021-1000000. Read below to understand the difference between CAN and CVE.

Using DWF_CAN and DWF_CVE (or some naming scheme like that to avoid confusion between Mitre-CVE and DWF-CVE) will remove the need for this "one million marks the end of Mitre CVE IDs". I am certain that you both have very thoughtfully decided upon 1 million being the cross-over point, but we can avoid it altogether! (and not potentially risk repeating a saga similar to IPv4 address exhaustion).  
What is the rational behind the magic number 1 million?

**Comment by joshbressers** [comment]
I think defining acronyms is a fair point. I'll fix up some docs in the near future to do that.

But as for the naming, that's a no.
CVE now means "vulnerability" in the same way a tissue is a kleenex.
If we create a "new" naming scheme we end up with
https://xkcd.com/927/
But if we reuse an existing naming scheme, there isn't an increase in identifiers names.

We have staked out a claim well outside a range that could possible be a concern, that's why the 1 million. It's a huge number that probably won't have any collisions (possibly ever, but at least for decades).

**Comment by joshbressers** [comment]
I added this question to the FAQ
https://github.com/distributedweaknessfiling/dwf-workflow/commit/4d66a9fb7891e48f62b3c5124df54907ce47271a#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cf
